name: Auto Update

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Use CI folder
        run: cd ci

      - name: Install dependencies
        run: pnpm install

      - name: Run index.js
        run: node index.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated using Github Actions
